### ISSUE TITLE
Add license headers to generated files.

### ISSUE THREAD

**Issue by NelsonDaniel** [Azure/autorest.powershell#140]

**Comment by dolauli** [comment]
p2

**Comment by dolauli** [comment]
[11/11 11:21 AM] Xiaogang Ding
    
Hi Garrett, I notice there is a configuration called "license-header", which is used to add license header for source code generated. So I add something like "license-header: MICROSOFT_MIT_NO_VERSION" in the configuration, but it does not work. Is this function broke in autorest v3?

[11/12 12:13 AM] Garrett Serack
    V2 Generators got that from the autorest.common library -- it's on my list to add that to autorest-core in v3 so that the license is available in the configuration

**Comment by dolauli** [comment]
This should be implemented in autorest.core.

**Comment by dolauli** [comment]
@fearthecowboy Please fix it as your earliest convenience since it blocks us from releasing to the public

**Comment by fearthecowboy** [comment]
I have added the code to autorest-core to support header text values 



To use this version:
Ensure that you're on `@autorest/autorest` `3.0.6141` or greater:
`npm install -g @autorest/autorest`

and then do a `--reset` and get the specific `autorest-core` package version `3.0.6168`:
`autorest-beta --version:3.0.6168`

then you can ask for the `header-text` configuration value (so when `--license-header`  is specified, it will return the appropriate text

**Comment by dolauli** [comment]
@fearthecowboy 
It still does not work. BTW, the latest core version seems to be 3.0.6158 instead of 3.0.6168. And the configuration I specify in my readme.md is` license-header: MICROSOFT_MIT_NO_VERSION`

**Comment by fearthecowboy** [comment]
*******************************************************************
# Ensure that you're on `@autorest/autorest` `3.0.6141` or greater:
*******************************************************************

👀  `npm install -g @autorest/autorest`

_(which as of this moment, will install `3.0.6146`)_

*******************************************************************
# the lastest version of the autorest-beta package has updates that are required in order to access pre-release versions of autorest-core. 
*******************************************************************

The latest PRERELEASE version (ie, not pushed to NPM) is downloaded from https://github.com/Azure/autorest/releases in order to allow for significant regression testing before publishing. 

from my sample generator 
``` typescript
 // example: do something here.
    let text = "A source file\n";

    const headerText = await session.getValue("header-text", "NO HEADER TEXT?");

    text = text + headerText;

```
and when you get the value for `header-text` it will be:
> Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the MIT License. See License.txt in the project root for license information.
Code generated by Microsoft (R) AutoRest Code Generator.
Changes may cause incorrect behavior and will be lost if the code is regenerated.

As you can see, it's in the output:
![image](https://user-images.githubusercontent.com/133736/70551672-d12b2c80-1b2c-11ea-8e8f-ab2a11c1cd75.png)

**Comment by dolauli** [comment]
My bad. I mixed up the autorest and autorest.core version. I will have a try in the autorest.powershell generator. BTW, considering to add license header is a common requirement for all generators, can we implement it in a common plugin instead that each generator will have to write the license header by itself. @fearthecowboy

**Comment by fearthecowboy** [comment]
Given that each language has a different comment style, that is virtually impossible.
