### ISSUE TITLE
Add support for key/value storage and random generation in tests

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#512]
## Description

To successfully record tests in Azure, it is necessary to store parameter values that determine the request URIs in the test recording for replay.  It is also necessary for tests to use randomness (especially in name generation) in order to execute robustly in Azure.  Add the following elemtns to the test capabilities in generated cmdlets

- [ ] General mechanism for storing/retrieving key value pairs in the test recording
- [ ] Automatically record the subscriptionId, and tenant in the test recording, and set these as default values for cmdlets in the scope of the tests (likely using $PSDefaultParameterValues)
- [ ] Cmdlet to generate a random seed.  In record mode,  generate, store, and return the random seed.  In playback mode, retrieve the random seed from the recording and return.
- [ ] Wrapper cmdlet for Get-Random that will call the cmdlet above and return random values based on the returned seed

### Cost: 6

**Comment by dolauli** [comment]
Something design thoughts as below.

- [ ] General mechanism for storing/retrieving key value pairs in the test recording
We need two json files here. One as input for -Live and -record mode with some configurations users may need to provide.
A sample is as below.
`{"SubscriptionId":"xxxxx", "randomParameters":["rdName"]}`
For randomParameters, we will randomly generate values for them when test.
The second is as input for -playback mode and output for -record mode(This file need to be checked in because it will be used in playback test).
A sample is as below.
`{"SubscriptionId":"xxxxx", "rdName":"something-autogenerated"]}`
And in the test code, we may use something like $SubscriptionId and $rdName to refer to values.
- [ ] Automatically record the subscriptionId, and tenant in the test recording, and set these as default values for cmdlets in the scope of the tests (likely using $PSDefaultParameterValues)
This could been done. Question here is why we need the tenant. It could be retrieved from TokenCache.dat, and we do not need to provide that.
- [ ] Cmdlet to generate a random seed. In record mode, generate, store, and return the random seed. In playback mode, retrieve the random seed from the recording and return.
- [ ] Wrapper cmdlet for Get-Random that will call the cmdlet above and return random values based on the returned seed
I suggest we just use the current time(epoch time) as seed instead of implementing a Cmdlet to generate a random seed. And in record mode, we will generate, store and return the values instead of the seed.

**Comment by dolauli** [comment]
@markcowl

**Comment by markcowl** [comment]
@dolauli  Yes, random seed is not necessary if all values are recorded and retrieved.  TenantId is used as a parameter in some cmdlets (for example, graph) and treated similarly to subscriptionId

**Comment by dolauli** [comment]
P1

**Comment by dolauli** [comment]
Already resolved.
