### ISSUE TITLE
Unwanted Function Exported Causing Namespace Conflict

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/autorest.powershell#741]
The new autorest.powershell has a breaking change in for the following Autorest versions:
'@autorest/powershell' (~3.0.0->3.0.421)
'@autorest/modelerfour' (4.15.414->4.15.414)

We had a "where" clause that is supposed to remove the conflicting command 'Update-AzsEncryption':

```
- where:
      verb: Update
      subject: SubscriptionEncryption
    remove: True
```

The old Autorest versions removed  'Update-AzsEncryption', but the new ones did not as it still ended up in our .psd1 file that was generated for our .nupkg. Here is our README.md:
https://github.com/Azure/azurestack-powershell/blob/master/src/Azs.Subscriptions.Admin/readme.md

This caused the commandlet namespace conflict error below:

```
PS C:\Users\Administrator> 
Install-Module -Name Azs.Subscriptions.Admin -RequiredVersion 1.0.0 -Repository az-azs
PackageManagement\Install-Package : The following commands are already available on this 
system:'Update-AzsEncryption'. This module 'Azs.Subscriptions.Admin' may override the existing commands. If you still 
want to install this module 'Azs.Subscriptions.Admin', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9711 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],  
   Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.Pack 
   ageManagement.Cmdlets.InstallPackage
```

**Comment by bganapa** [comment]
@dolauli followed up in a email 


This change starts from m4 generator (3.0.+).
 
The root cause of the issue is in the operationId. Normally, the operationId should follow the format as below.
 
[group]-[operation]
 
But as you could see from the swagger, the operationId of update-AzsEncryption is without [group].
 
        "tags": [
          "Subscriptions"
        ],
        "operationId": "UpdateEncryption",
 
To follow the operationId naming rule, it should be changed to “Subscriptions-UpdateEncryption”. And I also find some other operationIds that do not follow this rule. E.g. RestoreData, CheckIdentityHealth.
 
And why this works in previous version is because in previous modeler, if [group] is not provided, we will use the value in “tags” as [group], but this behavior changed in m4, the [group] will be empty if it is not provided. 
 
  - $key: ''  // here the value of $key is ‘’,  which is because the [group] is not provided in the operationId.
    operations:
      - apiVersions:
          - version: '2015-11-01'
        parameters:


Considering remodeler (m3) autorest team has stopped maintaining remodeler(m3). I strongly recommend your team starts to use the latest autorest.powershell based on m4.
 
For this specific issue, I think it should be easy to fix by adding [group] in the oeprationId.

**Comment by dolauli** [comment]
Workaround provided.
