### ISSUE TITLE
Parameter Mandatory not correct

### ISSUE THREAD

**Issue by dicolanl** [Azure/autorest.powershell#799]
See #715 

Running against swagger: https://github.com/Azure/azure-rest-api-specs/blob/7601061bfbb72b2f19cb29c46cbf9a397c2d8893/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/stable/2020-01-01/Bookmarks.json#L328
Line 328 shows DisplayName is required.

but when generated displayName is not mandatory
![image](https://user-images.githubusercontent.com/25964057/124849058-ebb8c800-df52-11eb-96e8-32791a4e8aa7.png)

Since swagger is correct, how do I fix this?

just noticed this is happening for a bunch of parameters.

**Comment by dolauli** [comment]
It is not a bug, but by design. For your case, this is because https://github.com/Azure/azure-rest-api-specs/blob/7601061bfbb72b2f19cb29c46cbf9a397c2d8893/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/stable/2020-01-01/Bookmarks.json#L232 is not required. If you want a property is required, you will need to have required chain. For example, c is part of b, b is part of a, you need to have a, b, c all required to make the generated parameter for c is required.

**Comment by dicolanl** [comment]
@dolauli 
Question. Is there a way to make it required using directives?

**Comment by dolauli** [comment]
No, we do not have directive for that. Besides making it required is incorrect according to the swagger.

**Comment by dolauli** [comment]
And you should change the swagger to mark  https://github.com/Azure/azure-rest-api-specs/blob/7601061bfbb72b2f19cb29c46cbf9a397c2d8893/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/stable/2020-01-01/Bookmarks.json#L232 as required.
