### ISSUE TITLE
How to invoke hidden cmdlets from custom C# cmdlets?

### ISSUE THREAD

**Issue by valterc** [Azure/autorest.powershell#943]
Hi, I'm trying to invoke hidden cmdlets from a custom cmdlet developed in C#. 

Since the auto generated cmdlets inherit from PSCmdlet one cannot just create a new instance and call Invoke (and seems like there is no way to change the base class type?). I've been trying multiple ways to execute the generated cmdlets, like `InvokeCommand.InvokeScript(@"MyModule.internal\Hidden-Command")` without much success, always getting the error: 
> The module 'MyModule.internal' could not be loaded.

From a custom powershell cmdlet simply doing `MyModule.internal\Hidden-Command` works fine, the command executes, but from custom C# cmdlets I haven't found a working way. Does anyone know a way to do this?

**Comment by dolauli** [comment]
You can not do that in your custom C# cmdlet because the module {module}.internal is not loaded as the error tells. You can do that in custom PowerShell script is because we use 'import-module Az.{module}.internal.psm1' in az.{module}.custom.psm1. Instead, you could call the backend Client API directly in your C# custom cmdlet.

**Comment by valterc** [comment]
Thanks, that's what I ended up doing 🙂
